name: This is a long naming for the workflow

on:
  push:
  workflow_dispatch:
    inputs:
      secret_version:
          description: 'Secret version'
          default: '10'
          required: true
    
env:
  SECRET_VERSION: 9

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: checks
        run: |
          echo "$SECRET_VERSION  --- VARS"
          echo "${{ inputs.secret_version }}  -- inputs"
