name: This is a long naming for the workflow

on:
  push:
  workflow_dispatch:
    inputs:
      secret_version:
          description: 'Secret version'
          default: '10'
          required: true
    
env:
  SECRET_DEFAULT_VERSION: 9

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: checks
        run: |
          if [[ -z "${{ inputs.secret_version }}" ]]; then
            SECRET_VERSION = $SECRET_DEFAULT_VERSION
          else
            SECRET_VERION = ${{ inputs.secrets_version }}
          fi
          echo "SECRET VERSION = $SECRET_VERSION"
