name: Test Tag

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+(-beta)?'
jobs:
  build-linux-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get beta vars
	if: contains(github.ref, 'beta')
	run: |
	  echo "Getting env vars for beta..."
      - name: Get Prod vars
	if:  !contains(github.ref, 'beta')
	run: |
	  echo "Getting prod vars"   
